package Kelompok8;


import static Kelompok8.WarungPedia.ID_USER;
import static Kelompok8.WarungPedia.Status;
import java.awt.Graphics;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Image;
import static java.awt.Image.SCALE_SMOOTH;
import java.awt.Toolkit;
import java.io.File;
import java.nio.file.Files;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class fiturPembeli extends javax.swing.JFrame {
private static int counter;
private static String foto;
private static int ID_U;
    /**
     * Creates new form fiturPembeli
     */
    public fiturPembeli() {
        initComponents();
        
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        WarungPedia Login = new WarungPedia();
        Tampilan_Awal BRG = new Tampilan_Awal();
        String ID = Login.ID_USER;
        int ID_BRG = BRG.ID_BRG;
        
        try {
            String sql = "SELECT * FROM barang WHERE ID_BARANG = '"+ID_BRG+"'";
            Connection level = (Connection)Koneksi.configDB();
            Statement gmt = level.createStatement();
            ResultSet ra = gmt.executeQuery(sql);
            while(ra.next()){
                lb_nama_barang.setText(ra.getString("NAMA_BARANG"));
                lb_stok.setText(ra.getString("STOK"));
                int STK = Integer.parseInt(lb_stok.getText());
                harga.setText(ra.getString("HARGA"));
                jTextArea1.setText(ra.getString("DESKRIPSI"));
                foto = ra.getString("Foto_Barang");
                File f = new File(this.foto);
                ImageIcon icon = new ImageIcon(f.toString());
                Image newimg = icon.getImage().getScaledInstance(577, 660, SCALE_SMOOTH);
                ImageIcon ic = new ImageIcon(newimg);
                lb_gambar_barang.setText("");
                lb_gambar_barang.setIcon(ic);
                if (STK == 0) {
                    lb_stok.setText("Habis");
                    btn_beli.setEnabled(false);
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        


        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lb_gambar_barang = new javax.swing.JLabel();
        lb_nama_barang = new javax.swing.JLabel();
        lb_jumlah_terjual = new javax.swing.JLabel();
        lb_harga = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btn_beli = new javax.swing.JButton();
        harga = new javax.swing.JLabel();
        lb_stok = new javax.swing.JLabel();
        lb_back = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(1341, 952));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(577, 952));

        lb_gambar_barang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_gambar_barang.setText("Gambar");
        lb_gambar_barang.setPreferredSize(new java.awt.Dimension(577, 660));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_gambar_barang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lb_gambar_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
        );

        lb_nama_barang.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        lb_nama_barang.setText("Nama Barang");

        lb_jumlah_terjual.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lb_jumlah_terjual.setText("STOK :");

        lb_harga.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        lb_harga.setText("Rp.");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setPreferredSize(new java.awt.Dimension(764, 516));
        jScrollPane1.setViewportView(jTextArea1);

        btn_beli.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        btn_beli.setText("Beli Sekarang");
        btn_beli.setPreferredSize(new java.awt.Dimension(206, 53));
        btn_beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_beliActionPerformed(evt);
            }
        });

        harga.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N

        lb_stok.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lb_nama_barang)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lb_jumlah_terjual)
                                .addGap(32, 32, 32)
                                .addComponent(lb_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lb_harga)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(harga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 457, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_beli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lb_nama_barang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_jumlah_terjual)
                    .addComponent(lb_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_harga)
                    .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btn_beli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        lb_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/pngwing 7.png"))); // NOI18N
        lb_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_backMouseClicked(evt);
            }
        });
        getContentPane().add(lb_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/download 3 (1).png"))); // NOI18N
        background.setText("jLabel3");
        background.setPreferredSize(new java.awt.Dimension(1440, 1024));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lb_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_backMouseClicked
        // TODO add your handling code here:
        Tampilan_Awal toko = new Tampilan_Awal();
        toko.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lb_backMouseClicked

    private void btn_beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_beliActionPerformed
        // TODO add your handling code here:
        WarungPedia Login = new WarungPedia();
        Tampilan_Awal BRG = new Tampilan_Awal();
        String ID = Login.ID_USER;
        int ID_Barang = BRG.ID_BRG;
        try {
            String sql = "SELECT * FROM User WHERE Username = '"+ID+"'";
            Connection level = (Connection)Koneksi.configDB();
            Statement gmt = level.createStatement();
            ResultSet ra = gmt.executeQuery(sql);
            if (counter < 2) {
                if(ra.next()){
                    String Level = ra.getString("Level");
                    if(Level.equals("Penjual")){
                        String penjual = "SELECT * FROM penjual WHERE Username = '"+ID+"'";
                        Connection kon = (Connection)Koneksi.configDB();
                        Statement stat = kon.createStatement();
                        ResultSet rst = stat.executeQuery(penjual);
                        while(rst.next()){
                            System.out.println("Lah");
                            ID_U = rst.getInt("ID_PENJUAL");
                            System.out.println("Aneh");
                        }
                        String keranjang_penjual = "INSERT INTO keranjang(ID_Barang, ID_Penjual, Status, TOTAL) VALUES ('"+ID_Barang+"','"+ID_U+"','Belum Checkout','"+harga.getText()+"')";
                        java.sql.Connection con = (Connection) Koneksi.configDB();
                        java.sql.PreparedStatement pst = con.prepareStatement(keranjang_penjual);
                        pst.execute();
                        Keranjang user = new Keranjang();
                        user.setVisible(true);
                        this.setVisible(false);
                    }else if(Level.equals("Pembeli")){
                        String penjual = "SELECT * FROM pembeli WHERE Username = '"+ID+"'";
                        Connection kon = (Connection)Koneksi.configDB();
                        Statement stat = kon.createStatement();
                        ResultSet rst = stat.executeQuery(penjual);
                        while(rst.next()){
                            ID_U = rst.getInt("ID_PEMBELI");
                        }
                        String keranjang_pembeli = "INSERT INTO keranjang(ID_Barang, ID_Pembeli, Status, TOTAL) VALUES ('"+ID_Barang+"','"+ID_U+"','Belum Checkout','"+harga.getText()+"')";
                        java.sql.Connection con = (Connection) Koneksi.configDB();
                        java.sql.PreparedStatement pst = con.prepareStatement(keranjang_pembeli);
                        pst.execute();
                        Keranjang user = new Keranjang();
                        user.setVisible(true);
                        this.setVisible(false);
                        

                    }else{
                        JOptionPane.showMessageDialog(this, "User belum login, harap login terlebih dahulu");
                        this.setVisible(false);
                        Login.setVisible(true);
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "User belum login, harap login terlebih dahulu");
                    counter++;
                }
            }else{
                JOptionPane.showMessageDialog(this, "Akses tidak Normal, Aplikasi akan ditutup!!");
                System.exit(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }        
    }//GEN-LAST:event_btn_beliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fiturPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fiturPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fiturPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fiturPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fiturPembeli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btn_beli;
    private javax.swing.JLabel harga;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lb_back;
    private javax.swing.JLabel lb_gambar_barang;
    private javax.swing.JLabel lb_harga;
    private javax.swing.JLabel lb_jumlah_terjual;
    private javax.swing.JLabel lb_nama_barang;
    private javax.swing.JLabel lb_stok;
    // End of variables declaration//GEN-END:variables
}
