/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Kelompok8;

import static Kelompok8.WarungPedia.ID_USER;
import java.awt.Image;
import static java.awt.Image.SCALE_SMOOTH;
import java.io.File;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author LiNuX112
 */
public class Pop_Up_Setelah_Login extends javax.swing.JFrame {

    /**
     * Creates new form Pop_Up_Setelah_Login
     */
    public Pop_Up_Setelah_Login() {
        initComponents();
        WarungPedia Login = new WarungPedia();
        String ID = Login.ID_USER;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Lb_Menu = new javax.swing.JLabel();
        Btn_Logout = new javax.swing.JButton();
        Btn_Keluar = new javax.swing.JButton();
        Btn_Keranjang = new javax.swing.JButton();
        Btn_Pengaturan = new javax.swing.JButton();
        Btn_Profil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(554, 294));

        Lb_Menu.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        Lb_Menu.setText("Menu");

        Btn_Logout.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        Btn_Logout.setText("Logout");
        Btn_Logout.setPreferredSize(new java.awt.Dimension(494, 85));
        Btn_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LogoutActionPerformed(evt);
            }
        });

        Btn_Keluar.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        Btn_Keluar.setText("Tutup");
        Btn_Keluar.setName(""); // NOI18N
        Btn_Keluar.setPreferredSize(new java.awt.Dimension(494, 85));
        Btn_Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_KeluarActionPerformed(evt);
            }
        });

        Btn_Keranjang.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        Btn_Keranjang.setText("Keranjang");
        Btn_Keranjang.setPreferredSize(new java.awt.Dimension(494, 85));
        Btn_Keranjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_KeranjangActionPerformed(evt);
            }
        });

        Btn_Pengaturan.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        Btn_Pengaturan.setText("Pengaturan");
        Btn_Pengaturan.setPreferredSize(new java.awt.Dimension(494, 85));
        Btn_Pengaturan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_PengaturanActionPerformed(evt);
            }
        });

        Btn_Profil.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        Btn_Profil.setText("Profil");
        Btn_Profil.setPreferredSize(new java.awt.Dimension(494, 85));
        Btn_Profil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ProfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Lb_Menu))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btn_Keluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Keranjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Pengaturan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Profil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lb_Menu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_Profil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Keranjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Pengaturan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Keluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_KeluarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_Btn_KeluarActionPerformed

    private void Btn_ProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ProfilActionPerformed
        // TODO add your handling code here:
        try {
            WarungPedia Login = new WarungPedia();
            String ID = Login.ID_USER;
            String sql = "SELECT * FROM User WHERE Username='"+ID+"'";
            Connection level = (Connection)Koneksi.configDB();
            Statement gmt = level.createStatement();
            ResultSet ra = gmt.executeQuery(sql);
            int counter = 0;
            
            if (counter < 2) {
                if(ra.next()){
                    String Level = ra.getString("Level");
                    
                    if(Level.equals("Penjual")){
                        Tampilan_Awal Awl = new Tampilan_Awal();
                        ProfilUser Penjual = new ProfilUser();
                        Awl.setVisible(false);
                        this.setVisible(false);
                        Penjual.setVisible(true);
                        

                    }else if(Level.equals("Pembeli")){
                        Tampilan_Awal Awl = new Tampilan_Awal();
                        ProfilPejual Pembeli = new ProfilPejual();
                        Awl.setVisible(false);
                        Pembeli.setVisible(true);
                        this.setVisible(false);
                        

                    }else{
                        JOptionPane.showMessageDialog(this, "User tidak ditemukan");
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Silahkan cek kembali username dan password anda!!");
                    counter++;
                }
            }else{
                JOptionPane.showMessageDialog(this, "Akses tidak Normal, Aplikasi akan ditutup!!");
                System.exit(0);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_Btn_ProfilActionPerformed

    private void Btn_KeranjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_KeranjangActionPerformed
        // TODO add your handling code here:
        Tampilan_Awal Awl = new Tampilan_Awal();
        Keranjang krajang = new Keranjang();
        Awl.setVisible(false);
        krajang.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Btn_KeranjangActionPerformed

    private void Btn_PengaturanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_PengaturanActionPerformed
        // TODO add your handling code here:
        try {
            WarungPedia Login = new WarungPedia();
            String ID = Login.ID_USER;
            String sql = "SELECT * FROM User WHERE Username='"+ID+"'";
            Connection level = (Connection)Koneksi.configDB();
            Statement gmt = level.createStatement();
            ResultSet ra = gmt.executeQuery(sql);
            int counter = 0;
            
            if (counter < 2) {
                if(ra.next()){
                    String Level = ra.getString("Level");
                    
                    if(Level.equals("Penjual")){
                        Tampilan_Awal Awl = new Tampilan_Awal();
                        Setting_Penjual pengaturan_penjual = new Setting_Penjual();
                        Awl.setVisible(false);
                        pengaturan_penjual.setVisible(true);
                        this.setVisible(false);

                    }else if(Level.equals("Pembeli")){
                        Tampilan_Awal Awl = new Tampilan_Awal();
                        Setting pengaturan_pembeli = new Setting();
                        Awl.setVisible(false);
                        pengaturan_pembeli.setVisible(true);
                        this.setVisible(false);
                        

                    }else{
                        JOptionPane.showMessageDialog(this, "User tidak ditemukan");
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Silahkan cek kembali username dan password anda!!");
                    counter++;
                }
            }else{
                JOptionPane.showMessageDialog(this, "Akses tidak Normal, Aplikasi akan ditutup!!");
                System.exit(0);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_Btn_PengaturanActionPerformed

    private void Btn_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LogoutActionPerformed
        // TODO add your handling code here:
        int jawab = JOptionPane.showOptionDialog(this,
            "Ingin Logout?",
            "LOGOUT",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE, null, null, null);

        if(jawab == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Akun telah diLogout");
            Tampilan_Awal Awl = new Tampilan_Awal();
            Awl.setVisible(false);
            WarungPedia login = new WarungPedia();
            login.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_Btn_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pop_Up_Setelah_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pop_Up_Setelah_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pop_Up_Setelah_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pop_Up_Setelah_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pop_Up_Setelah_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Keluar;
    private javax.swing.JButton Btn_Keranjang;
    private javax.swing.JButton Btn_Logout;
    private javax.swing.JButton Btn_Pengaturan;
    private javax.swing.JButton Btn_Profil;
    private javax.swing.JLabel Lb_Menu;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
