/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Kelompok8;

import com.mysql.cj.jdbc.PreparedStatementWrapper;
import java.awt.Graphics;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Image;
import static java.awt.Image.SCALE_SMOOTH;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.MediaTracker;
import java.io.IOException;
import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.sql.PreparedStatement;
/**
 *
 * @author LiNuX112
 */
public class ProfilUser extends javax.swing.JFrame {
    private PreparedStatement stat;
    private ResultSet rs;
    private static int counter;
    private Image image;
    private String filename;
    Koneksi k = new Koneksi();
    private String foto;
    /**
     * Creates new form ProfilUser
     */
    public ProfilUser() {
        initComponents();
        
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        WarungPedia Login = new WarungPedia();
        String ID = Login.ID_USER;
        
        try {
            String sql = "SELECT * FROM penjual WHERE Username = '"+ID+"'";
            Connection level = (Connection)Koneksi.configDB();
            Statement gmt = level.createStatement();
            ResultSet ra = gmt.executeQuery(sql);
            while(ra.next()){
                lb_name.setText(ra.getString("Nama_Toko"));
                lb_email_penjual.setText(ra.getString("Email_Toko"));
                lb_alamat_pejual.setText(ra.getString("Alamat_Toko"));
                lb_no_hp_penjual.setText(ra.getString("Telepon_Penjual"));
                foto = ra.getString("Logo_Toko");
                if (foto.equals("")) {
                    
                }else{
                File f = new File(this.foto);
                ImageIcon icon = new ImageIcon(f.toString());
                Image newimg = icon.getImage().getScaledInstance(369, 369, SCALE_SMOOTH);
                ImageIcon ic = new ImageIcon(newimg);
                lb_PP.setIcon(ic); 
                }
                
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
        
        
    }
    
    
    private void DTuser(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Utama = new javax.swing.JPanel();
        Panel_user_penjual = new javax.swing.JPanel();
        lb_profil = new javax.swing.JLabel();
        lb_email = new javax.swing.JLabel();
        lb_alamat = new javax.swing.JLabel();
        lb_no_hp = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lb_email_penjual = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lb_alamat_pejual = new javax.swing.JTextArea();
        lb_no_hp_penjual = new javax.swing.JLabel();
        lb_back = new javax.swing.JLabel();
        lb_PP = new javax.swing.JLabel();
        lb_name = new javax.swing.JLabel();
        lb_keranjang = new javax.swing.JLabel();
        lb_history = new javax.swing.JLabel();
        lb_setting = new javax.swing.JLabel();
        lb_tambah_produk = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1440, 1024));

        Panel_user_penjual.setBackground(new java.awt.Color(255, 255, 255));
        Panel_user_penjual.setMinimumSize(new java.awt.Dimension(726, 662));

        lb_profil.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        lb_profil.setText("Profil");

        lb_email.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        lb_email.setText("Email");

        lb_alamat.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        lb_alamat.setText("Alamat");

        lb_no_hp.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        lb_no_hp.setText("No HP");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel6.setText(":");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel7.setText(":");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel8.setText(":");

        lb_email_penjual.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        lb_email_penjual.setText("211111003@mhs.stiki.ac.id");

        lb_alamat_pejual.setEditable(false);
        lb_alamat_pejual.setColumns(20);
        lb_alamat_pejual.setFont(new java.awt.Font("Segoe UI", 0, 35)); // NOI18N
        lb_alamat_pejual.setRows(5);
        jScrollPane1.setViewportView(lb_alamat_pejual);

        lb_no_hp_penjual.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        lb_no_hp_penjual.setText("087857172381");

        javax.swing.GroupLayout Panel_user_penjualLayout = new javax.swing.GroupLayout(Panel_user_penjual);
        Panel_user_penjual.setLayout(Panel_user_penjualLayout);
        Panel_user_penjualLayout.setHorizontalGroup(
            Panel_user_penjualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_user_penjualLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel_user_penjualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_user_penjualLayout.createSequentialGroup()
                        .addGroup(Panel_user_penjualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_profil)
                            .addComponent(lb_email)
                            .addComponent(lb_alamat))
                        .addGap(58, 58, 58))
                    .addGroup(Panel_user_penjualLayout.createSequentialGroup()
                        .addComponent(lb_no_hp)
                        .addGap(8, 8, 8)))
                .addGroup(Panel_user_penjualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_user_penjualLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(lb_email_penjual))
                    .addGroup(Panel_user_penjualLayout.createSequentialGroup()
                        .addGroup(Panel_user_penjualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(Panel_user_penjualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lb_no_hp_penjual, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Panel_user_penjualLayout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(8, 8, 8)))))
                .addContainerGap())
        );
        Panel_user_penjualLayout.setVerticalGroup(
            Panel_user_penjualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_user_penjualLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_profil)
                .addGap(88, 88, 88)
                .addGroup(Panel_user_penjualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_email)
                    .addComponent(jLabel6)
                    .addComponent(lb_email_penjual))
                .addGap(18, 18, 18)
                .addGroup(Panel_user_penjualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_user_penjualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb_alamat)
                        .addComponent(jLabel7))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(Panel_user_penjualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_no_hp_penjual)
                    .addComponent(jLabel8)
                    .addComponent(lb_no_hp))
                .addGap(36, 36, 36))
        );

        lb_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/pngwing 7.png"))); // NOI18N
        lb_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_backMouseClicked(evt);
            }
        });

        lb_PP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_PP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Picsart_22-09-26_16-04-45-131.png"))); // NOI18N
        lb_PP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_PPMouseClicked(evt);
            }
        });

        lb_name.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        lb_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_name.setText("Warung Pedia");

        lb_keranjang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/kisspng-shopping-cart-logo-shopping-bags-trolleys-5afb65b0c66925 1.png"))); // NOI18N
        lb_keranjang.setPreferredSize(new java.awt.Dimension(103, 117));
        lb_keranjang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_keranjangMouseClicked(evt);
            }
        });

        lb_history.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/newsletter-line.png"))); // NOI18N
        lb_history.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_historyMouseClicked(evt);
            }
        });

        lb_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/pngegg 1.png"))); // NOI18N
        lb_setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_settingMouseClicked(evt);
            }
        });

        lb_tambah_produk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Vector.png"))); // NOI18N
        lb_tambah_produk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_tambah_produkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout UtamaLayout = new javax.swing.GroupLayout(Utama);
        Utama.setLayout(UtamaLayout);
        UtamaLayout.setHorizontalGroup(
            UtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UtamaLayout.createSequentialGroup()
                .addComponent(lb_back)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(UtamaLayout.createSequentialGroup()
                .addGroup(UtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UtamaLayout.createSequentialGroup()
                        .addGroup(UtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_PP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(UtamaLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lb_keranjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb_history)
                        .addGap(18, 18, 18)
                        .addComponent(lb_setting)
                        .addGap(18, 18, 18)
                        .addComponent(lb_tambah_produk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)))
                .addComponent(Panel_user_penjual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        UtamaLayout.setVerticalGroup(
            UtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UtamaLayout.createSequentialGroup()
                .addComponent(lb_back)
                .addGap(103, 103, 103)
                .addGroup(UtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(UtamaLayout.createSequentialGroup()
                        .addComponent(lb_PP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_name)
                        .addGap(106, 106, 106)
                        .addGroup(UtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UtamaLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(UtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_history)
                                    .addComponent(lb_keranjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_setting)))
                            .addComponent(lb_tambah_produk)))
                    .addComponent(Panel_user_penjual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(292, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lb_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_backMouseClicked
        // TODO add your handling code here:
        Tampilan_Awal toko = new Tampilan_Awal();
        toko.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lb_backMouseClicked

    private void lb_keranjangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_keranjangMouseClicked
        // TODO add your handling code here:
        Keranjang keranjang = new Keranjang();
        keranjang.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lb_keranjangMouseClicked

    private void lb_historyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_historyMouseClicked
        // TODO add your handling code here:
        PesananSaya history = new PesananSaya();
        history.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lb_historyMouseClicked

    private void lb_settingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_settingMouseClicked
        // TODO add your handling code here:
        Setting_Penjual pengaturan = new Setting_Penjual();
        pengaturan.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lb_settingMouseClicked

    private void lb_tambah_produkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_tambah_produkMouseClicked
        // TODO add your handling code here:
        Tambah_Produk tambah = new Tambah_Produk();
        tambah.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lb_tambah_produkMouseClicked

    private void lb_PPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_PPMouseClicked
        // TODO add your handling code here:
        //System.out.println("tes");
        try{
            WarungPedia Login = new WarungPedia();
            String ID = Login.ID_USER;
            String sql = "SELECT * FROM penjual WHERE Username='"+ID+"'";
            Connection level = (Connection)Koneksi.configDB();
            Statement gmt = level.createStatement();
            ResultSet ra = gmt.executeQuery(sql);
            
            if (counter < 2) {
                if(ra.next()){
                    String Level = ra.getString("Logo_Toko");
                    System.out.println(Level);
                    if(Level.equals(null)){
                        JFileChooser fc=new JFileChooser(); 
                        fc.showOpenDialog(this); 
                        File f=fc.getSelectedFile();
                        ImageIcon PP = new ImageIcon(f.toString());
                        Image img = PP.getImage().getScaledInstance(369, 369, SCALE_SMOOTH);
                        ImageIcon profil = new ImageIcon(img);
                        lb_PP.setIcon(profil);
                        this.filename = f.getAbsolutePath();
                        int jawab = JOptionPane.showOptionDialog(this, 
                            "Simpan Hasil Ubah?", 
                            "Simpan", 
                        JOptionPane.YES_NO_OPTION, 
                        JOptionPane.QUESTION_MESSAGE, null, null, null);
                        if(jawab == JOptionPane.YES_OPTION){
                            String patch = "src/PP_Penjual";
                            System.out.println("tes"+patch);
                            File directory = new File(patch);
                            File fileawal = null;
                            File fileakhir = null;
                            String ext = this.filename.substring(filename.lastIndexOf('.')+1);
                            fileawal = new File(filename);
                            fileakhir = new File(patch+"/"+lb_name.getText()+"."+ext);
                            System.out.println(ID);
                            this.stat = Koneksi.configDB().prepareStatement("UPDATE pembeli set Logo_Toko='"+"src"+"/"+"PP_Penjual"+"/"+lb_name.getText()+"."+ext+"' WHERE Username='"+ID+"'");
                            stat.executeUpdate();
                            JOptionPane.showMessageDialog(this, "Foto berhasil diubah");
                            Files.copy(fileawal.toPath(), fileakhir.toPath());
                         }
                    }else{
                        JFileChooser fc=new JFileChooser(); 
                        fc.showOpenDialog(this); 
                        File f=fc.getSelectedFile();
                        ImageIcon PP = new ImageIcon(f.toString());
                        Image img = PP.getImage().getScaledInstance(369, 369, SCALE_SMOOTH);
                        ImageIcon profil = new ImageIcon(img);
                        lb_PP.setIcon(profil);
                        this.filename = f.getAbsolutePath();
                        int jawab = JOptionPane.showOptionDialog(this, 
                            "Simpan Hasil Ubah?", 
                            "Simpan", 
                        JOptionPane.YES_NO_OPTION, 
                        JOptionPane.QUESTION_MESSAGE, null, null, null);
                        if(jawab == JOptionPane.YES_OPTION){
                            String patch = "src/PP_Penjual";
                            System.out.println("tes"+patch);
                            File directory = new File(patch);
                            File fileawal = null;
                            File fileakhir = null;
                            String ext = this.filename.substring(filename.lastIndexOf('.')+1);
                            fileawal = new File(filename);
                            fileakhir = new File(patch+"/"+lb_name.getText()+"."+ext);
                            System.out.println(ID);
                            this.stat = Koneksi.configDB().prepareStatement("UPDATE penjual set Logo_Toko='"+"src"+"/"+"PP_Penjual"+"/"+lb_name.getText()+"."+ext+/*fileakhirtemporary.getText()+*/"' WHERE Username='"+ID+"'");
                            stat.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Foto berhasil diubah");
                            Files.copy(fileawal.toPath(), fileakhir.toPath());
                        }
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Silahkan cek kembali username dan password anda!!");
                    counter++;
                }
            }else{
                JOptionPane.showMessageDialog(this, "Akses tidak Normal, Aplikasi akan ditutup!!");
                System.exit(0);
            }
            }catch(Exception e){
            System.out.println(e.getMessage());
            }
    }//GEN-LAST:event_lb_PPMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfilUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfilUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfilUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfilUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfilUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_user_penjual;
    private javax.swing.JPanel Utama;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_PP;
    private javax.swing.JLabel lb_alamat;
    private javax.swing.JTextArea lb_alamat_pejual;
    private javax.swing.JLabel lb_back;
    private javax.swing.JLabel lb_email;
    private javax.swing.JLabel lb_email_penjual;
    private javax.swing.JLabel lb_history;
    private javax.swing.JLabel lb_keranjang;
    private javax.swing.JLabel lb_name;
    private javax.swing.JLabel lb_no_hp;
    private javax.swing.JLabel lb_no_hp_penjual;
    private javax.swing.JLabel lb_profil;
    private javax.swing.JLabel lb_setting;
    private javax.swing.JLabel lb_tambah_produk;
    // End of variables declaration//GEN-END:variables
}
