/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Kelompok8;

import javax.swing.JOptionPane;
import java.awt.Graphics;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Image;
import static java.awt.Image.SCALE_SMOOTH;
import java.awt.Toolkit;
import java.io.File;
import java.nio.file.Files;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JPanel;
/**
 *
 * @author LiNuX112
 */
public class RegisterPenjual extends javax.swing.JFrame {
private Image image;
private String filename;
private String foto;
    /**
     * Creates new form RegisterPenjual
     */
    public RegisterPenjual() {
        initComponents();
        
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Utama = new javax.swing.JPanel();
        lb_register = new javax.swing.JLabel();
        lb_Username = new javax.swing.JLabel();
        lb_Password = new javax.swing.JLabel();
        lb_NamaToko = new javax.swing.JLabel();
        lb_Alamat = new javax.swing.JLabel();
        lb_Email = new javax.swing.JLabel();
        fld_Username = new javax.swing.JTextField();
        fld_NamaToko = new javax.swing.JTextField();
        fld_Email = new javax.swing.JTextField();
        fld_Alamat = new javax.swing.JTextField();
        btn_Register = new javax.swing.JButton();
        fld_Password = new javax.swing.JPasswordField();
        lb_Telepon = new javax.swing.JLabel();
        fld_Telepon = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Utama.setPreferredSize(new java.awt.Dimension(1047, 919));

        lb_register.setFont(new java.awt.Font("Segoe UI", 1, 70)); // NOI18N
        lb_register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_register.setText("PENDAFTARAN");

        lb_Username.setFont(new java.awt.Font("Segoe UI", 0, 35)); // NOI18N
        lb_Username.setText("Username");

        lb_Password.setFont(new java.awt.Font("Segoe UI", 0, 35)); // NOI18N
        lb_Password.setText("Password");

        lb_NamaToko.setFont(new java.awt.Font("Segoe UI", 0, 35)); // NOI18N
        lb_NamaToko.setText("Nama Toko");

        lb_Alamat.setFont(new java.awt.Font("Segoe UI", 0, 35)); // NOI18N
        lb_Alamat.setText("Alamat");

        lb_Email.setFont(new java.awt.Font("Segoe UI", 0, 35)); // NOI18N
        lb_Email.setText("Email");

        fld_Username.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        fld_Username.setPreferredSize(new java.awt.Dimension(473, 40));
        fld_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_UsernameActionPerformed(evt);
            }
        });

        fld_NamaToko.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        fld_NamaToko.setMinimumSize(new java.awt.Dimension(7, 40));
        fld_NamaToko.setPreferredSize(new java.awt.Dimension(473, 40));
        fld_NamaToko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_NamaTokoActionPerformed(evt);
            }
        });

        fld_Email.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        fld_Email.setPreferredSize(new java.awt.Dimension(473, 40));
        fld_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_EmailActionPerformed(evt);
            }
        });

        fld_Alamat.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        fld_Alamat.setPreferredSize(new java.awt.Dimension(473, 40));
        fld_Alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_AlamatActionPerformed(evt);
            }
        });

        btn_Register.setFont(new java.awt.Font("Segoe UI", 1, 35)); // NOI18N
        btn_Register.setText("DAFTAR");
        btn_Register.setPreferredSize(new java.awt.Dimension(262, 88));
        btn_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegisterActionPerformed(evt);
            }
        });

        fld_Password.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        fld_Password.setMinimumSize(new java.awt.Dimension(7, 40));
        fld_Password.setPreferredSize(new java.awt.Dimension(473, 40));
        fld_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_PasswordActionPerformed(evt);
            }
        });

        lb_Telepon.setFont(new java.awt.Font("Segoe UI", 0, 35)); // NOI18N
        lb_Telepon.setText("Telepon");

        fld_Telepon.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        fld_Telepon.setPreferredSize(new java.awt.Dimension(473, 40));
        fld_Telepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_TeleponActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButton1.setText("Foto");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout UtamaLayout = new javax.swing.GroupLayout(Utama);
        Utama.setLayout(UtamaLayout);
        UtamaLayout.setHorizontalGroup(
            UtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UtamaLayout.createSequentialGroup()
                .addContainerGap(298, Short.MAX_VALUE)
                .addGroup(UtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_Telepon)
                    .addComponent(fld_Telepon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_NamaToko)
                    .addComponent(lb_Username)
                    .addComponent(fld_Username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_Password)
                    .addComponent(lb_Email)
                    .addComponent(fld_Email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_Alamat)
                    .addComponent(fld_Alamat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fld_NamaToko, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fld_Password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(276, 276, 276))
        );
        UtamaLayout.setVerticalGroup(
            UtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UtamaLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lb_register)
                .addGap(1, 1, 1)
                .addComponent(lb_NamaToko)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fld_NamaToko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lb_Username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fld_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_Password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fld_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_Email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fld_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_Alamat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fld_Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_Telepon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fld_Telepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        getContentPane().add(Utama, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 75, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/download 2.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fld_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_UsernameActionPerformed

    private void fld_NamaTokoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_NamaTokoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_NamaTokoActionPerformed

    private void fld_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_EmailActionPerformed

    private void fld_AlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_AlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_AlamatActionPerformed

    private void btn_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegisterActionPerformed
        // TODO add your handling code here:
        if (fld_Username.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Nama masih kosong");
        }
        if (fld_Password.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Username masih kosong");
        }
        if (fld_NamaToko.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Password masih kosong");
        }
        if (fld_Email.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Email masih kosong");
        }if(fld_Alamat.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Alamat masih kosong");
        }if(fld_Telepon.getText().equals("")){
            JOptionPane.showMessageDialog(this, "No.Telepon masih kosong");
        }else {
            try {
                String patch = "src/PP_Penjual";
                File directory = new File(patch);
                File fileawal = null;
                File fileakhir = null;
                String ext = this.filename.substring(filename.lastIndexOf('.')+1);
                fileawal = new File(filename);
                fileakhir = new File(patch+"/"+fld_NamaToko.getText()+"."+ext);
                String pmbl = "Penjual";
                String penjual = "INSERT INTO user VALUES('" + fld_Username.getText() + "','"
                                    + fld_Password.getText() + "','"+pmbl+"')";
                String login = "INSERT INTO penjual(Username,Nama_Toko,Alamat_Toko,Email_Toko,Telepon_Penjual, Logo_Toko) VALUES('" + fld_Username.getText() + "','"+ fld_NamaToko.getText() +"'"
                        + ",'" + fld_Alamat.getText() + "','" + fld_Email.getText() + "','" + fld_Telepon.getText() +"', '"+"src"+"/"+"PP_Penjual"+"/"+fld_NamaToko.getText()+"."+ext+"')";
                java.sql.Connection con = (Connection) Koneksi.configDB();
                java.sql.PreparedStatement pst = con.prepareStatement(penjual);
                java.sql.PreparedStatement lgn = con.prepareStatement(login);
                pst.execute();
                lgn.execute();
                Files.copy(fileawal.toPath(), fileakhir.toPath());
                JOptionPane.showMessageDialog(this, "Akun berhasil dibuat, silakan login kembali");
                WarungPedia Login = new WarungPedia();
                Login.setVisible(true);
                this.setVisible(false);
                fld_Username.setText("");
                fld_NamaToko.setText("");
                fld_Alamat.setText("");
                fld_Email.setText("");
                fld_Password.setText("");
                fld_Telepon.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());

            }
        }
    }//GEN-LAST:event_btn_RegisterActionPerformed

    private void fld_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_PasswordActionPerformed

    private void fld_TeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_TeleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_TeleponActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        JFileChooser fc=new JFileChooser(); 
        fc.showOpenDialog(this); 
        File f=fc.getSelectedFile();
        ImageIcon PP = new ImageIcon(f.toString());
        Image img = PP.getImage().getScaledInstance(369, 369, SCALE_SMOOTH);
        ImageIcon profil = new ImageIcon(img);
        this.filename = f.getAbsolutePath();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPenjual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPenjual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPenjual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPenjual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPenjual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JPanel Utama;
    private javax.swing.JButton btn_Register;
    private javax.swing.JTextField fld_Alamat;
    private javax.swing.JTextField fld_Email;
    private javax.swing.JTextField fld_NamaToko;
    private javax.swing.JPasswordField fld_Password;
    private javax.swing.JTextField fld_Telepon;
    private javax.swing.JTextField fld_Username;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lb_Alamat;
    private javax.swing.JLabel lb_Email;
    private javax.swing.JLabel lb_NamaToko;
    private javax.swing.JLabel lb_Password;
    private javax.swing.JLabel lb_Telepon;
    private javax.swing.JLabel lb_Username;
    private javax.swing.JLabel lb_register;
    // End of variables declaration//GEN-END:variables
}
