/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Kelompok8;


import java.awt.Graphics;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Image;
import static java.awt.Image.SCALE_SMOOTH;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author LiNuX112
 */
public class Tambah_Produk extends javax.swing.JFrame {
    private Image image;
    private String filename;
    Koneksi k = new Koneksi();
    private String foto;
    private PreparedStatement stat;
    private ResultSet rs;
    private int ID_P;
    private int ID_B;
    /**
     * Creates new form Tambah_Produk
     */
    public Tambah_Produk() {
         initComponents();
        
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        WarungPedia Login = new WarungPedia();
        String ID = Login.ID_USER;
       
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
        
        try {
            String sql = "SELECT * FROM penjual WHERE Username='"+ID+"'";
                                Connection level = (Connection)Koneksi.configDB();
                                Statement gmt = level.createStatement();
                                ResultSet ra = gmt.executeQuery(sql);
                                while(ra.next()){
                                    ID_P = ra.getInt("ID_Penjual");
                                    }
        } catch (Exception e) {
        }
        System.out.println(ID_P);
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        HARGA = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        DESKRIPSI = new javax.swing.JTextArea();
        lb_harga = new javax.swing.JLabel();
        lb_nama_produk = new javax.swing.JLabel();
        lb_stok = new javax.swing.JLabel();
        lb_deskripsi = new javax.swing.JLabel();
        STOK = new javax.swing.JTextField();
        Nama_barang = new javax.swing.JTextField();
        btn_tambah = new javax.swing.JButton();
        lb_gambar = new javax.swing.JLabel();
        lb_back = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        pnl_gambar2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1440, 1024));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HARGA.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        HARGA.setPreferredSize(new java.awt.Dimension(220, 44));
        jPanel1.add(HARGA, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 680, 220, -1));

        DESKRIPSI.setColumns(20);
        DESKRIPSI.setRows(5);
        DESKRIPSI.setPreferredSize(new java.awt.Dimension(1027, 358));
        jScrollPane1.setViewportView(DESKRIPSI);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 1010, 290));

        lb_harga.setFont(new java.awt.Font("Segoe UI", 1, 35)); // NOI18N
        lb_harga.setText("Harga");
        jPanel1.add(lb_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 670, -1, -1));

        lb_nama_produk.setFont(new java.awt.Font("Segoe UI", 1, 35)); // NOI18N
        lb_nama_produk.setText("Nama Produk");
        jPanel1.add(lb_nama_produk, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        lb_stok.setFont(new java.awt.Font("Segoe UI", 1, 35)); // NOI18N
        lb_stok.setText("Stock");
        jPanel1.add(lb_stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 750, -1, -1));

        lb_deskripsi.setFont(new java.awt.Font("Segoe UI", 1, 35)); // NOI18N
        lb_deskripsi.setText("Deskripsi Produk");
        jPanel1.add(lb_deskripsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        STOK.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        STOK.setPreferredSize(new java.awt.Dimension(220, 44));
        jPanel1.add(STOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 760, -1, -1));

        Nama_barang.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        Nama_barang.setPreferredSize(new java.awt.Dimension(1027, 56));
        jPanel1.add(Nama_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        btn_tambah.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        jPanel1.add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 830, 340, -1));

        lb_gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/capture-20221009-182741 1.png"))); // NOI18N
        lb_gambar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_gambarMouseClicked(evt);
            }
        });
        jPanel1.add(lb_gambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 230, -1));

        lb_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/pngwing 7.png"))); // NOI18N
        lb_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_backMouseClicked(evt);
            }
        });
        jPanel1.add(lb_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/download 2.png"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -10, 1440, -1));

        pnl_gambar2.setPreferredSize(new java.awt.Dimension(214, 200));

        javax.swing.GroupLayout pnl_gambar2Layout = new javax.swing.GroupLayout(pnl_gambar2);
        pnl_gambar2.setLayout(pnl_gambar2Layout);
        pnl_gambar2Layout.setHorizontalGroup(
            pnl_gambar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        pnl_gambar2Layout.setVerticalGroup(
            pnl_gambar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jPanel1.add(pnl_gambar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 230, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lb_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_backMouseClicked
        // TODO add your handling code here:
        ProfilUser penjual = new ProfilUser();
        penjual.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lb_backMouseClicked

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        WarungPedia Login = new WarungPedia();
        String ID = Login.ID_USER;
        System.out.println(ID);
       if (Nama_barang.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Nama masih kosong");
        }
        if (DESKRIPSI.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Username masih kosong");
        }
        if (HARGA.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Password masih kosong");
        }
        if (STOK.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Email masih kosong");
        
        }else {
            int jawab = JOptionPane.showOptionDialog(this, 
                            "Pastikan data yang anda masukkan benar!!", 
                            "YA", 
                        JOptionPane.YES_NO_OPTION, 
                        JOptionPane.QUESTION_MESSAGE, null, null, null);
                        if(jawab == JOptionPane.YES_OPTION){
                            try {
                            String patch = "src/Foto_Barang";
                            File directory = new File(patch);
                            File fileawal = null;
                            File fileakhir = null;
                            String ext = this.filename.substring(filename.lastIndexOf('.')+1);
                            fileawal = new File(filename);
                            fileakhir = new File(patch+"/"+Nama_barang.getText()+"."+ext);
                            String login = "INSERT INTO barang(ID_Penjual,NAMA_BARANG,HARGA,STOK,Deskripsi, Foto_Barang) VALUES('" +ID_P+ "','"+ Nama_barang.getText() +"'"
                                        + ",'" + HARGA.getText() + "','" + STOK.getText() + "','"+DESKRIPSI.getText()+"','"+"src"+"/"+"Foto_Barang"+"/"+Nama_barang.getText()+"."+ext+"')";
                            java.sql.Connection con = (Connection) Koneksi.configDB();
                            java.sql.PreparedStatement lgn = con.prepareStatement(login);
                            lgn.execute();
                            Files.copy(fileawal.toPath(), fileakhir.toPath());
                            /*String sql = "SELECT * FROM barang WHERE NAMA_BARANG='"+Nama_barang.getText()+"'";
                            Connection level = (Connection)Koneksi.configDB();
                            Statement gmt = level.createStatement();
                            ResultSet ra = gmt.executeQuery(sql);
                                while (ra.next()) {
                                    ID_B = ra.getInt("ID_BARANG");
                                }
                                System.out.println(ID_B);
                                System.out.println(ID_P);
                                String pembeli = "UPDATE barang SET NAMA_BARANG='"+Nama_barang.getText()+"',HARGA='"+HARGA.getText()+"'"
                                        + ",STOK='"+STOK.getText()+"',DESKRIPSI='"+DESKRIPSI.getText()+"'WHERE ID_PENJUAL = '"+ID_P+"' AND NAMA_BARANG ='"+Nama_barang.getText()+"'";
                            java.sql.Connection con = (Connection) Koneksi.configDB();
                            java.sql.PreparedStatement pst = con.prepareStatement(pembeli);
                            pst.execute();*/ 
                            } catch (Exception e) {
                                JOptionPane.showMessageDialog(null, e);
                            }
                            ProfilUser profil = new ProfilUser();
                            profil.setVisible(true);
                            this.setVisible(false);
                            JOptionPane.showMessageDialog(this, "Produk berhasil di tambah");
                            Nama_barang.setText("");
                            DESKRIPSI.setText("");
                            HARGA.setText("");
                            STOK.setText("");
                        }
            }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void lb_gambarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_gambarMouseClicked
        // TODO add your handling code here:
        JFileChooser fc=new JFileChooser(); 
        fc.showOpenDialog(this); 
        File f=fc.getSelectedFile();
        ImageIcon PP = new ImageIcon(f.toString());
        Image img = PP.getImage().getScaledInstance(228, 200, SCALE_SMOOTH);
        ImageIcon profil = new ImageIcon(img);
        lb_gambar.setIcon(profil);
        this.filename = f.getAbsolutePath();
        /*WarungPedia Login = new WarungPedia();
        String ID = Login.ID_USER;
        if (Nama_barang.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Nama masih kosong");
        }else{
            JFileChooser fc=new JFileChooser(); 
                        fc.showOpenDialog(this); 
                        File f=fc.getSelectedFile();
                        ImageIcon PP = new ImageIcon(f.toString());
                        Image img = PP.getImage().getScaledInstance(228, 200, SCALE_SMOOTH);
                        ImageIcon profil = new ImageIcon(img);
                        lb_gambar.setIcon(profil);
                        this.filename = f.getAbsolutePath();
                        int jawab = JOptionPane.showOptionDialog(this, 
                            "Simpan Gambar?", 
                            "Simpan", 
                        JOptionPane.YES_NO_OPTION, 
                        JOptionPane.QUESTION_MESSAGE, null, null, null);
                        if(jawab == JOptionPane.YES_OPTION){
                            String patch = "src/Foto_Barang";
                            File directory = new File(patch);
                            File fileawal = null;
                            File fileakhir = null;
                            String ext = this.filename.substring(filename.lastIndexOf('.')+1);
                            fileawal = new File(filename);
                            fileakhir = new File(patch+"/"+Nama_barang.getText()+"."+ext);
                            try {
                            this.stat = Koneksi.configDB().prepareStatement("INSERT INTO barang(ID_PENJUAL, NAMA_BARANG, Foto_Barang) VALUES('"+ID_P+"','"+Nama_barang.getText()+"','"+"src"+"/"+"Foto_Barang"+"/"+Nama_barang.getText()+"."+ext+"')");
                            stat.executeUpdate();
                            JOptionPane.showMessageDialog(this, "Foto berhasil disimpan");
                            Files.copy(fileawal.toPath(), fileakhir.toPath());
                            } catch (Exception e) {
                                JOptionPane.showMessageDialog(this, e);
                            }
                        }
        }*/
    }//GEN-LAST:event_lb_gambarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tambah_Produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tambah_Produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tambah_Produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tambah_Produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tambah_Produk().setVisible(true);
            }
        });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea DESKRIPSI;
    private javax.swing.JTextField HARGA;
    private javax.swing.JTextField Nama_barang;
    private javax.swing.JTextField STOK;
    private javax.swing.JLabel background;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_back;
    private javax.swing.JLabel lb_deskripsi;
    private javax.swing.JLabel lb_gambar;
    private javax.swing.JLabel lb_harga;
    private javax.swing.JLabel lb_nama_produk;
    private javax.swing.JLabel lb_stok;
    private javax.swing.JPanel pnl_gambar2;
    // End of variables declaration//GEN-END:variables
}

