/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Kelompok8;

import java.awt.Graphics;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Image;
import static java.awt.Image.SCALE_SMOOTH;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
/**
 *
 * @author LiNuX112
 */
public class Tampilan_Awal extends javax.swing.JFrame {
    DefaultTableModel DTB;
    public static String NM_BRG;
    public static int ID_BRG;
    /**
     * Creates new form Tampilan_Awal
     */
    public Tampilan_Awal() {
        initComponents();
        DTB = (DefaultTableModel) TB_Barang.getModel();
        
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
        load_data();
    }
    
    private void load_data() {
        DefaultTableModel DT = new DefaultTableModel();
        DT.addColumn("Nama Barang");
        DT.addColumn("Harga");
        DT.addColumn("Stok");
        try {
            String sql = "SELECT NAMA_BARANG, HARGA, STOK FROM barang ORDER BY ID_BARANG";
            java.sql.Connection con = (Connection) Koneksi.configDB();
            java.sql.Statement stm = con.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                DT.addRow(new Object[]{res.getString(1), res.getString(2),
                    res.getString(3)});
            }
            TB_Barang.setModel(DT);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPopupMenu();
        Login = new javax.swing.JMenuItem();
        Tutup = new javax.swing.JMenuItem();
        Utama = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TB_Barang = new javax.swing.JTable();
        Panel_WarungPedia = new javax.swing.JPanel();
        lb_logo = new javax.swing.JLabel();
        fld_search = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        btn_profil = new javax.swing.JButton();
        lb_WarungPedia = new javax.swing.JLabel();
        lb_terlaris = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        Menu.setToolTipText("");
        Menu.setAlignmentX(871.0F);
        Menu.setAlignmentY(173.0F);
        Menu.setAutoscrolls(true);
        Menu.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu"));
        Menu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Menu.setMinimumSize(new java.awt.Dimension(554, 296));
        Menu.setName("Menu"); // NOI18N
        Menu.setNextFocusableComponent(btn_profil);
        Menu.setPreferredSize(new java.awt.Dimension(554, 296));

        Login.setText("Login");
        Menu.add(Login);

        Tutup.setText("Tutup");
        Menu.add(Tutup);

        Menu.getAccessibleContext().setAccessibleName("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1440, 1024));

        Utama.setMinimumSize(new java.awt.Dimension(1440, 1024));
        Utama.setPreferredSize(new java.awt.Dimension(1440, 1024));
        Utama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TB_Barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        )
        {
            public boolean isCellEditable(int row, int column){
                return false;
            }
        }
    );
    TB_Barang.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            TB_BarangMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(TB_Barang);

    Utama.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 1410, 740));

    Panel_WarungPedia.setBackground(new java.awt.Color(255, 255, 255));
    Panel_WarungPedia.setMinimumSize(new java.awt.Dimension(1440, 167));
    Panel_WarungPedia.setPreferredSize(new java.awt.Dimension(1440, 167));

    lb_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Picsart_22-09-26_16-04-45-131 1.png"))); // NOI18N

    fld_search.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
    fld_search.setMinimumSize(new java.awt.Dimension(453, 65));
    fld_search.setPreferredSize(new java.awt.Dimension(453, 65));
    fld_search.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            fld_searchActionPerformed(evt);
        }
    });

    btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/search-26232 1.png"))); // NOI18N
    btn_search.setPreferredSize(new java.awt.Dimension(96, 79));
    btn_search.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_searchActionPerformed(evt);
        }
    });

    btn_profil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/kisspng-computer-icons-user-material-design-my-account-icon-5ad833c105fee9 1.png"))); // NOI18N
    btn_profil.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_profilActionPerformed(evt);
        }
    });

    lb_WarungPedia.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
    lb_WarungPedia.setText("WarungPedia");

    javax.swing.GroupLayout Panel_WarungPediaLayout = new javax.swing.GroupLayout(Panel_WarungPedia);
    Panel_WarungPedia.setLayout(Panel_WarungPediaLayout);
    Panel_WarungPediaLayout.setHorizontalGroup(
        Panel_WarungPediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(Panel_WarungPediaLayout.createSequentialGroup()
            .addComponent(lb_logo)
            .addGap(18, 18, 18)
            .addComponent(lb_WarungPedia)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
            .addComponent(fld_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_profil)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );
    Panel_WarungPediaLayout.setVerticalGroup(
        Panel_WarungPediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(Panel_WarungPediaLayout.createSequentialGroup()
            .addComponent(lb_logo)
            .addGap(0, 5, Short.MAX_VALUE))
        .addGroup(Panel_WarungPediaLayout.createSequentialGroup()
            .addGap(47, 47, 47)
            .addGroup(Panel_WarungPediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(fld_search, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Panel_WarungPediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_search, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(btn_profil, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(Panel_WarungPediaLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lb_WarungPedia))))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    Utama.add(Panel_WarungPedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 160));

    lb_terlaris.setBackground(new java.awt.Color(255, 255, 255));
    lb_terlaris.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
    lb_terlaris.setText("LIST BARANG");
    Utama.add(lb_terlaris, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

    Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/download 2.png"))); // NOI18N
    Utama.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(Utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(Utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fld_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_searchActionPerformed

    private void btn_profilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_profilActionPerformed
        // TODO add your handling code here:
            WarungPedia Login = new WarungPedia();
            String ID = Login.ID_USER;
            String Log = Login.Status;
            if (Log.equals("Belum Login")) {
                Pop_Up menu = new Pop_Up();
                menu.setVisible(true);
            }else{
                Pop_Up_Setelah_Login menu_login = new Pop_Up_Setelah_Login();
                menu_login.setVisible(true);
            }
        
    }//GEN-LAST:event_btn_profilActionPerformed

    private void TB_BarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TB_BarangMouseClicked
        // TODO add your handling code here
        int baris = TB_Barang.rowAtPoint(evt.getPoint());
        NM_BRG = TB_Barang.getValueAt(baris, 0).toString();
        System.out.println(NM_BRG);
        try {
            String sql = "SELECT * FROM barang WHERE NAMA_BARANG = '"+NM_BRG+"'";
            Connection level = (Connection)Koneksi.configDB();
            Statement gmt = level.createStatement();
            ResultSet ra = gmt.executeQuery(sql);
            while(ra.next()){
                ID_BRG = ra.getInt("ID_BARANG");
                }
        }catch (Exception e) {
        }
        System.out.println(ID_BRG);
        fiturPembeli DTL_BRG = new fiturPembeli();
        DTL_BRG.setVisible(true);
        this.setVisible(false);
   
    }//GEN-LAST:event_TB_BarangMouseClicked

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        if (fld_search.getText().equals("")) {
            load_data();
        }else{
            String NMBRG = fld_search.getText();
            DefaultTableModel DT = new DefaultTableModel();
            DT.addColumn("Nama Barang");
            DT.addColumn("Harga");
            DT.addColumn("Stok");
            try {
                String sql = "SELECT NAMA_BARANG, HARGA, STOK FROM barang WHERE NAMA_BARANG LIKE '"+NMBRG+"' ORDER BY ID_BARANG";
                java.sql.Connection con = (Connection) Koneksi.configDB();
                java.sql.Statement stm = con.createStatement();
                java.sql.ResultSet res = stm.executeQuery(sql);
                while (res.next()) {
                    DT.addRow(new Object[]{res.getString(1), res.getString(2),
                        res.getString(3)});
                }
                TB_Barang.setModel(DT);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e);
            }
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tampilan_Awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tampilan_Awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tampilan_Awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tampilan_Awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tampilan_Awal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JMenuItem Login;
    private javax.swing.JPopupMenu Menu;
    private javax.swing.JPanel Panel_WarungPedia;
    private javax.swing.JTable TB_Barang;
    private javax.swing.JMenuItem Tutup;
    private javax.swing.JPanel Utama;
    private javax.swing.JButton btn_profil;
    private javax.swing.JButton btn_search;
    private javax.swing.JTextField fld_search;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_WarungPedia;
    private javax.swing.JLabel lb_logo;
    private javax.swing.JLabel lb_terlaris;
    // End of variables declaration//GEN-END:variables

}
