/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Kelompok8;

import java.awt.Graphics;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Image;
import static java.awt.Image.SCALE_SMOOTH;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
/**
 *
 * @author LiNuX112
 */
public class WarungPedia extends javax.swing.JFrame {
    
    private static int counter;
    /**
     * Creates new form WarungPedia
     */
    
    public static String ID_USER;
    public static String Status = "Belum Login";
    
    
    
    public WarungPedia() {
        initComponents();
        
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;
        //ID_USER = "tc";
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        Appnama = new javax.swing.JLabel();
        lb_username = new javax.swing.JLabel();
        lb_password4 = new javax.swing.JLabel();
        fld_username = new javax.swing.JTextField();
        btn_Login = new javax.swing.JButton();
        lb_donthaveaccount = new javax.swing.JLabel();
        fld_password = new javax.swing.JPasswordField();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel.setAlignmentX(166.0F);
        Panel.setAlignmentY(75.0F);
        Panel.setMinimumSize(new java.awt.Dimension(829, 833));
        Panel.setPreferredSize(new java.awt.Dimension(829, 833));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Picsart_22-09-26_16-04-45-131.png"))); // NOI18N
        Logo.setText("jLabel1");
        Logo.setMinimumSize(new java.awt.Dimension(369, 369));
        Logo.setPreferredSize(new java.awt.Dimension(369, 284));

        Appnama.setFont(new java.awt.Font("Segoe UI", 3, 60)); // NOI18N
        Appnama.setText("Warung Pedia");
        Appnama.setAlignmentX(485.0F);
        Appnama.setAlignmentY(325.0F);

        lb_username.setFont(new java.awt.Font("Segoe UI", 0, 35)); // NOI18N
        lb_username.setText("Username");
        lb_username.setAlignmentX(2.0F);

        lb_password4.setFont(new java.awt.Font("Segoe UI", 0, 35)); // NOI18N
        lb_password4.setText("Password");
        lb_password4.setAlignmentX(2.0F);

        fld_username.setFont(new java.awt.Font("Segoe UI", 0, 33)); // NOI18N
        fld_username.setText("HoGaMeN112");
        fld_username.setPreferredSize(new java.awt.Dimension(496, 58));
        fld_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_usernameActionPerformed(evt);
            }
        });

        btn_Login.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn_Login.setText("LOGIN");
        btn_Login.setPreferredSize(new java.awt.Dimension(496, 86));
        btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoginActionPerformed(evt);
            }
        });

        lb_donthaveaccount.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lb_donthaveaccount.setText("Don't Have Account");
        lb_donthaveaccount.setPreferredSize(new java.awt.Dimension(495, 26));
        lb_donthaveaccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_donthaveaccountMouseClicked(evt);
            }
        });

        fld_password.setFont(new java.awt.Font("Segoe UI", 0, 33)); // NOI18N

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(Appnama)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(243, 243, 243))
            .addGroup(PanelLayout.createSequentialGroup()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(lb_donthaveaccount, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fld_username, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                            .addComponent(lb_password4)
                            .addComponent(lb_username)
                            .addComponent(btn_Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fld_password))))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Appnama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_username)
                .addGap(19, 19, 19)
                .addComponent(fld_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_password4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fld_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btn_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_donthaveaccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(61, 61, 61))
        );

        getContentPane().add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Cara-Kerja-OLSHOP 1.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lb_donthaveaccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_donthaveaccountMouseClicked
        // TODO add your handling code here:
        Register register = new Register();
        register.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lb_donthaveaccountMouseClicked

    private void btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoginActionPerformed
        // TODO add your handling code here:
        
        WarungPedia tx = new WarungPedia();
        tx.ID_USER = fld_username.getText();
        if (fld_username.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Username masih kosong");
        }if (fld_password.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Password masih kosong");
        }else{
            try{
            String sql = "select * from user where Username='"+fld_username.getText()+"' and Password='"+fld_password.getText()+"'";
            Connection level = (Connection)Koneksi.configDB();
            Statement gmt = level.createStatement();
            ResultSet ra = gmt.executeQuery(sql);

            if (counter < 2) {
                if(ra.next()){
                    String Level = ra.getString("Level");
                    
                    if(Level.equals("Penjual")){
                        /*Tampilan_Awal Tampilan_Awal = new Tampilan_Awal();
                        Tampilan_Awal.setVisible(true);*/
                        ProfilUser Penjual = new ProfilUser();
                        Penjual.setVisible(true);
                        this.setVisible(false);
                        ID_USER = fld_username.getText();
                        Status = "Login";
                        

                    }else if(Level.equals("Pembeli")){
                        /*Tampilan_Awal Tampilan_Awal = new Tampilan_Awal();
                        Tampilan_Awal.setVisible(true);
                        this.setVisible(false);*/
                        ProfilPejual Pembeli = new ProfilPejual();
                        Pembeli.setVisible(true);
                        this.setVisible(false);
                        ID_USER = fld_username.getText();
                        Status = "Login";
                        

                    }else{
                        JOptionPane.showMessageDialog(this, "Username atau Password Salah!!!");
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Silahkan cek kembali username dan password anda!!");
                    counter++;
                }
            }else{
                JOptionPane.showMessageDialog(this, "Akses tidak Normal, Aplikasi akan ditutup!!");
                System.exit(0);
            }
            }catch(Exception e){
            System.out.println(e.getMessage());
            }
        }
        
    }//GEN-LAST:event_btn_LoginActionPerformed

    private void fld_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WarungPedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WarungPedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WarungPedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WarungPedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WarungPedia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Appnama;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel Panel;
    private javax.swing.JButton btn_Login;
    private javax.swing.JPasswordField fld_password;
    private javax.swing.JTextField fld_username;
    private javax.swing.JLabel lb_donthaveaccount;
    private javax.swing.JLabel lb_password4;
    private javax.swing.JLabel lb_username;
    // End of variables declaration//GEN-END:variables
}
